server:
  port: 8087
  
  
spring:
  application:
    name: server-config
   
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Akhtarvaseem/Microservices-server-config.git
          clone-on-start: true
          
 
       
eureka:
   instance:
    ip-address: true
   client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8085/eureka